# Autogenerated wrapper script for Box2D_jll for x86_64-apple-darwin
export libbox2d

JLLWrappers.@generate_wrapper_header("Box2D")
JLLWrappers.@declare_library_product(libbox2d, "@rpath/libbox2d.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbox2d,
        "lib/libbox2d.2.4.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
