# Autogenerated wrapper script for Box2D_jll for x86_64-w64-mingw32
export libbox2d

JLLWrappers.@generate_wrapper_header("Box2D")
JLLWrappers.@declare_library_product(libbox2d, "libbox2d.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbox2d,
        "bin\\libbox2d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
